# Docker Compose for MyData operator services
version: "2"
services:
#  web:
#    build: ./ui
#    links:
#      - service
#    ports:
#      - "80:80"
  service:
    build: ./service
    links:
      - mongo
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"