# Docker Compose for MyData operator services
version: "2"
services:
  web:
    build: service
    volumes:
      - "./service:/service"
    links:
      - mongo
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"