# Docker Compose for MyData operator services
version: "2"
services:
 # web:
  #  build: https://github.com/Maankoodauskurssi/mydata-operator-front.git
  #  links:
  #    - service
  #  ports:
  #    - "80:3000"
  service:
    build: ./service
    links:
      - mongo
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"