---
swagger: "2.0"
info:
  version: "0.1 Maankoodauskurssi"
  title: "MyData operator api"
basePath: "/api"
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
paths:
  /consent/request:
    post:
      description: Creates a new request for a consent.
      parameters:
        - name: request
          in: body
          description: An array of consents linked to the same consent request.
          schema:
            type: array
            items:
              $ref: '#/definitions/request'
          required: true
      responses:
        200:
          description: "Returns Consent Receipt ID and status of the request."

  /consent/request/{requestId}:
    get:
      description: |
        Gets detailed consent request information, defined by consent ID.
      parameters:
        - name: requestId
          in: path
          description: The request Id.
          type: string
          required: true
      responses:
        200:
          description: Response content.
          schema:
            $ref: "#/definitions/request"
        404:
          description: "Resource unavailable"

  /consent/receipt:
    post:
      description: "Creates a new consent receipt."
      responses:
        200:
          description: "Returns Consent Receipt ID and status of the request."
          schema:
            type: string
            description: "JWT token of the consent receipt request."
    get:
      description: "Gets detailed consent receipt data."
      parameters:
        - name: subjectId
          in: query
          type: string
          description: "Id of the consent subject (the data owner)"
          required: true
      responses:
        200:
          description: "Returns all consent receipts for given user."
          schema:
            $ref: "#/definitions/Receipt"
            
        


  /consent/receipt/{consentId}:
    get:
      description: |
        Gets full information about the consent receipt and its status, determined by the consentId parameter.
      parameters:
        - name: consentId
          in: path
          type: string
          description: Id of the consent receipt.
          required: true
      responses:
        200:
          description: "Returns Consent Receipt ID and status of the request."
          schema:
            type: string
            description: JWT token of the consent receipt request.

definitions:
  Receipt:
    type: object
    properties:
      consentType:
        type: string
        description: "String indicating the type of consent: receipt, notice or request."
      Header:
        $ref: "#/definitions/Header"
      DataController:
        $ref: "#/definitions/DataController"
      Services:
        $ref: "#/definitions/Services"
        
  Request:
    type: object
    properties:
      header:
        $ref: "#/definitions/header"
      dataController:
        $ref: "#/definitions/dataController"
      services:
        $ref: "#/definitions/services"
        
  header:
    type: object
    properties:
      version:
        type: string
        description: This indicates what version of the Kantara specification this receipt conforms to.
      jurisdiction:
        type: string
      iat:
        type: integer
      moc:
        type: string
        description: A description of the method by which consent was obtained.
      jti:
        type: string
        description: JWT ID generated by the party creating the initial consent or request.
      publicKey:
        type: string
      sub:
        type: string
        description: Subject provided identifier, email address - or Claim, defined/namespace.
      sensitive:
        type: boolean
      spiCat:
        type: array
        items: {}
        
  dataController:
    type: object
    properties:
      onBehalf:
        type: boolean
      contact:
        type: string
      org:
        type: string
      address:
        type: string
      email:
        type: string
      phone:
        type: string

  services:
    type: array
    items:
      type: object
      properties:
        serviceName:
          type: string
        policyUrl:
          type: string
        purposes:
          type: array
          items:
            type: object
            properties:
              purpose:
                type: string
              consentType:
                type: string
              purposeCategory:
                type: array
                items:
                  type: string
              piiCategory:
                type: array
                items:
                  type: string
              nonCorePurpose:
                type: boolean
              purposeTermination:
                type: string
              thirdPartyDisclosure:
                type: boolean
              thirdPartyName:
                type: string
